### ISSUE TITLE
1992年廣州話讀音表有四字有錄入錯誤

### ISSUE THREAD

**Issue by leimaau** [ktshek/cantonese-books-data#4]
不好意思打攪了，「育」，「蔭」，「沒」，「幢」，這四字數據有問題，另外「踩」字cai2可能陋了一個a，「俠hap3」是否應該是hap6？

**Comment by ktshek** [comment]
確認俠、幢、育、踩是手民之誤，蔭則是不察《異讀》書有誤，均須改正。
另「爍」字聲調亦有錯，將同時修正。
