### ISSUE TITLE
typographical corrections for '1855_初學粵音切要'

### ISSUE THREAD

**Issue by HayaoAkiyama** [ktshek/cantonese-books-data#5]
Column "字"
48:阻⇒詛
94:円⇒丹
539:𦕎⇒盻
614:昗⇒冥
741:橯⇒撈
888:𦋐⇒罩
937:跪⇒詭
938:詭⇒跪
1000:刧⇒劫
1050:棳⇒掇
1247:宭⇒窘
1271:窹⇒寤
1510:圼⇒𬛸 (U+2C6F8, ⿱臼工)
1803:慺⇒樓
1811:櫻⇒攖
1999:槫⇒摶
2312:旱⇒旰
2326:开⇒幵
2741:騖⇒鶩
3910:遞⇒遁

Columns of "反切"
284 醯:審何⇒醯:可希
318 琴:共金⇒琴:其金
319 耹:共金⇒耹:其金
320 妗:共審⇒妗:其審
329 軫:之申⇒軫:之忍
658 紛:扶艮⇒紛:非申
659 氛:扶艮⇒氛:非申
660 芬:扶艮⇒芬:非申
686 別:並別⇒別:丙別
874 卒:見出⇒卒:則出
946 惓:共全⇒惓:其全
964 原:言又⇒原:言全
965 嫄:言又⇒嫄:言全
966 源:言又⇒源:言全
1136 坷:下何⇒坷:可火
1384 喬:共夭⇒喬:其夭
1386 簥:共夭⇒簥:其夭
1387 轎:共夭⇒轎:其夭
1462 圂:喻國⇒圂:喻圂
1478 畦:共為⇒畦:其為
1808 屨:耒語⇒屨:其語
1809 窶:耒語⇒窶:其語
2200 扛:見當⇒扛:啟當
2211 拒:共語⇒拒:其語
2212 距:共語⇒距:其語
2213 矩:共語⇒矩:見語
2435 窮:共中⇒窮:其中
2436 穹:共中⇒穹:其中
2568 總:明總⇒總:則總
2714 岐:共希⇒岐:其希
2715 歧:共希⇒歧:其希
2716 伎:共希⇒伎:其希
2792 擎:共丁⇒擎:其丁
2811 芹:共申⇒芹:其申
2893 草:太老⇒草:七老
3439 湯:大當⇒湯:太當
3581 猋:並夭⇒猋:丙夭
3582 飈:並夭⇒飈:丙夭
4167 縣:下金⇒縣:下全
4168 懸:下金⇒懸:下全
4346 娟:烏全⇒娟:見全
4347 捐:烏全⇒捐:見全
4348 涓:烏全⇒涓:見全
4498 痕:見申⇒痕:下申
5094 誾:岸中⇒誾:岸申
5385 鳥:尼水⇒鳥:尼小
5386 裊:尼水⇒裊:尼小

From: Hayao Akiyama

**Comment by ktshek** [comment]
感謝指正，資料檔會在稍後更新。

**Comment by ktshek** [comment]
有關 `1000:刧⇒劫` 項，由於本字如此，所以保持不變，請諒。

changeset 並有其他修正，包括：
(1) 補回「㐱」字部及字條，原「珍」字部改為從此部。
(2) 補回「分：扶艮」讀音條
(3) 修正「距」字讀音（與拒字同樣錯誤）
