### ISSUE TITLE
1855_初學粵音切要: 錯漏更正

### ISSUE THREAD

**Issue by HayaoAkiyama** [ktshek/cantonese-books-data#7]
字
1669:⿰犭央->㹧
1882:詑->詫
2962:啺->暘
3505:矄->曛
3675:涌->湧
4189:謠->遙
4451:瘐->庾
4517:墾->懇
4641:滍->嗤
4850:簣->蕢
4874:檳->擯[𢷤]
5113:閒->間
5190:⿱雍正->㻾 (原文印刷不清)
5407:麁->麄

切音
608:冖:明息->冖:門息
637:處:丑語->處[処]:丑去
1254:窘:共圂->窘:啟圂
1486:畦:共為->畦:其爲
3543:斧:扶苦->斧:非苦
3544:釜:扶苦->釜:非苦
3880:愠:烏國->愠[慍]:烏圂
4413:藏:則當->藏:前當
4440:臼:共九->臼:其九
4441:舅:共九->舅:其九
4620:䖍:共天->䖍:其天
4664:依:烏哀->依:英希
4695:襾:烏西->襾:烏亞

遺漏:
24頁13行: 擡:同哀

**Comment by ktshek** [comment]
謝謝。有兩處未改：

```
5190:⿱雍正->㻾 (原文印刷不清)
```
印本「工」字左方明顯有一豎筆，實在兩難。容我再考慮一下。

```
608:冖:明息->冖:門息
```
原文有註指出「門」不是反切上字，所以改作明。由於只有此字條有此情況，遂決定改正字條而非添加反切上字。

**Comment by wtn** [comment]
⿰育攵 → U+3054E 𰕎 ([UTC-01157](https://hc.jsecs.org/irg/ws2015/app/?id=01501), [chart](https://www.unicode.org/charts/PDF/Unicode-13.0/U130-30000.pdf))

**Comment by jyutnet** [comment]
Done, thank you @wtn.
