### ISSUE TITLE
1855_初學粵音切要: 三組形近字

### ISSUE THREAD

**Issue by HayaoAkiyama** [ktshek/cantonese-books-data#8]
1025: 殳 ->**𠬛**(U+20B1B):明末
有別於3325**殳**:時於。

5418:痳 ->**痲**:耒金
有別於3181**痳**:明加

4877:賣->**𧶠**(U+27DA0):由卜
有別於4858**賣**:明界

**Comment by ktshek** [comment]
已改正，謝謝。
